version: "2"

services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - /Users/aveiga/.docker_volumes/postgres:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
  keycloak:
    image: jboss/keycloak
    restart: always
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      DB_VENDOR: postgres
      DB_ADDR: postgres:5432
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - postgres